name: $(Date:yyyy)$(Date:.M)$(Date:.d)$(Rev:.r)-nightly

trigger: none
pr: none
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - develop

stages:
  - stage: StudioNugetBuild
    displayName: "Build Studio and Nugets"
    jobs:
      - template: "templates/build-nugets.yml"
        parameters:
          buildConfiguration: Release
          buildVersion: "$(Build.BuildNumber)"
          publishEnabled: true
          publishFeed: "Evergine.Nightly"
